version: '3'
services:
    consul-server-leader:
        image: consul:latest
        restart: always
        container_name: consul-server-leader
        command: "agent -server -bootstrap -ui -node=consul-server-leader -client=0.0.0.0 -bind=0.0.0.0"
        volumes:
            - ./conf:/consul/config
            - ./data:/consul/data
        environment:
            - CONSUL_BIND_INTERFACE=eth0
            - 'CONSUL_LOCAL_CONFIG={"connect": {"enabled": true}}'
        ports:
            - "8500:8500"
