version: '3'
services:
    redis:
        image: redis:6.0.10
        restart: always
        container_name: redis
        privileged: true
        command: redis-server /etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - ./redis.conf:/etc/redis/redis.conf
            - ./data:/data
